version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: root
    group: root
    mode : 755
    
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 300
      runas: root
